version: "3"

# This compose file only sends predefined arguments to the controller
# This is made to skip the user input, but otherwise should work exactly as the original docker-compose

services:
  alpr:
    build: ./
    command: "src/controller.py eu vurdering"
    stdin_open: true
    tty: true
    volumes:
      - ./input_videos:/input_videos
      - ./export_files:/export_files