

INPUT_ALPR_ALG = "alpr"

INPUT_CODE_EUROPE = "eu"
INPUT_CODE_USA = "us"
INPUT_CODE_AUSTRALIA = "au"

INPUT_FORMAT_CSV = ".csv"

INPUT_FORMAT_SEMICOLON = ";"

INPUT_SORT_TIME =  "tid"
INPUT_SORT_CONFIDENCE = "vurdering"