name: ALPR Test CI

on:
  pull_request:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build, run, test and tear down
      run: |
        mv ./test_clip.mp4 /input_videos
        docker-compose -f docker-compose.test.yml build
        docker-compose -f docker-compose.test.yml run alpr
        docker-compose -f docker-compose.test.yml down -v
        rm /input_videos/test_clip.mp4