name: ALPR Test CI

on:
  pull_request:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and run a test example
      run: |
        cp "./test_clip.mp4" "./input_videos"
        docker-compose -f docker-compose.test.yml build
        docker-compose -f docker-compose.test.yml run alpr
        docker-compose -f docker-compose.test.yml down -v
        rm "./input_videos/test_clip.mp4"

  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.7.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .
    - name: run automated tests
      run: python -m pytest